import { Then, When } from '@cucumber/cucumber';
import { buildCustomerProfile, wrongPasswordFor } from '../factories/customer.factory';
import { expect } from '../support/assertions';
import type { ParaBankWorld } from '../support/world';

When('I sign in with my credentials', async function (this: ParaBankWorld) {
  const { username, password } = this.session.profile;
  await this.pages.home.open();
  await this.pages.home.signIn(username, password);
});

When('I sign in with an incorrect password', async function (this: ParaBankWorld) {
  const { profile } = this.session;
  await this.pages.home.open();
  await this.pages.home.signIn(profile.username, wrongPasswordFor(profile));
});

When('I sign in with a username that is not registered', async function (this: ParaBankWorld) {
  // A fresh synthetic profile is never registered: its username is unique by construction.
  const { username, password } = buildCustomerProfile();
  await this.pages.home.signIn(username, password);
});

When('I sign in with my username but no password', async function (this: ParaBankWorld) {
  await this.pages.home.open();
  await this.pages.home.signIn(this.session.profile.username, '');
});

When('I open my accounts overview page directly', async function (this: ParaBankWorld) {
  await this.page.goto('overview.htm');
  // The page renders its answer after loading: a message (refusal or error) or the accounts.
  await this.pages.feedback.errors.first().or(this.pages.overview.accountRows.first()).waitFor();
  this.outcomeSettled = true;
});

When(
  'I request my login information with all my identity details',
  async function (this: ParaBankWorld) {
    const { profile } = this.session;
    await this.pages.customerLookup.open();
    await this.pages.customerLookup.requestLoginInfo(profile);
  },
);

When(
  'I request login information for identity details that match no customer',
  async function (this: ParaBankWorld) {
    // The 9xx area is never issued as an SSN and never generated by the customer factory, so
    // this identity cannot belong to any customer (including through the SSN-only lookup defect).
    await this.pages.customerLookup.requestLoginInfo({
      ...buildCustomerProfile(),
      ssn: '999-00-0000',
    });
  },
);

When(
  "I request my login information with my SSN but another person's name and address",
  async function (this: ParaBankWorld) {
    const someoneElse = buildCustomerProfile({ firstName: 'Another', lastName: 'Person' });
    await this.pages.customerLookup.open();
    await this.pages.customerLookup.requestLoginInfo({
      ...someoneElse,
      address: { ...someoneElse.address, street: '999 Unrelated Road', city: 'Elsewhere' },
      ssn: this.session.profile.ssn,
    });
    // The answer is server-rendered and the action waited for that page to load.
    this.outcomeSettled = true;
  },
);

Then('I should be told my login information was located', async function (this: ParaBankWorld) {
  await expect(this.pages.customerLookup.locatedMessage).toBeVisible();
});

Then('the recovered username should be mine', async function (this: ParaBankWorld) {
  // Compared in memory; the message never contains either value.
  const recovered = await this.pages.customerLookup.recoveredUsername();
  expect(recovered === this.session.profile.username, 'recovered username is mine').toBe(true);
});

Then('I should be signed in to my own accounts', async function (this: ParaBankWorld) {
  await expect(this.pages.menu.logOutLink).toBeVisible();
  const response = await this.bank.accountsResponse(this.session.id);
  expect(response.status(), 'accounts endpoint status for this browser session').toBe(200);
});

When('I sign in without entering any credentials', async function (this: ParaBankWorld) {
  await this.pages.home.submitEmptySignIn();
});

When('I sign out', async function (this: ParaBankWorld) {
  await this.pages.menu.signOut();
});

Then('I should see my accounts overview', async function (this: ParaBankWorld) {
  const { overview } = this.pages;
  await expect(this.page).toHaveURL(/overview\.htm/);
  await expect(overview.heading).toBeVisible();
  // It must be *this* customer's data, not just any overview page.
  await expect(overview.accountRows).toHaveCount(1);
  await expect(overview.accountRows.getByRole('link')).toHaveText(
    String(this.session.primaryAccountId),
  );
});

Then(
  'I should be told that my credentials could not be verified',
  async function (this: ParaBankWorld) {
    await expect(this.pages.feedback.errors).toHaveText([
      'The username and password could not be verified.',
    ]);
  },
);

Then('I should be asked to enter a username and password', async function (this: ParaBankWorld) {
  await expect(this.pages.feedback.errors).toHaveText(['Please enter a username and password.']);
});
